### ISSUE TITLE
Review Week10

### ISSUE THREAD

**Issue by river1440-ce** [FetaPOP/Headline_Connector#25]

**Comment by tienyulin** [comment]
I've found a problem of your team about the way of using git from last week. 

Last week, you guys directly pushed all the changes to the remote `develop` branch from your local `develop` branch. Beware that `develop` branch should not be pushed directly from local, your changes should merge back to `develop` branch through PRs. `develop` branch is a branch just like `master`, but for testing and waiting for releasing.
Moreover, I've noticed that you guys still work on the same child branch. It's not recommended to work on the same child branch unless you're debugging for the code. It usually breaks and affects others' work if people work on the same child branch. I even create a child branch to fix the bugs then merge it back. 

So I highly recommend that don't touch the branch which does not belong to you. Always create a new child branch from `develop` to implement your new features.  Don't fear resolving conflicts, it happens sometimes while someone has updated the code to `develop` ahead of you then you have to merge the updated code from `develop` to your branch. 

Last but not least, I encourage you to create more child branches and PRs then merge them back to `develop` branch after finishing a feature or fixing a bug. Continuous updating and synchronizing your code to remote can reduce the burden of resolving conflicts when merging. You'll never want to resolve a bunch of conflicts since people keep updating their code and the code from remote has a huge difference with yours, this project is small tho. And people usually screw some features when resolving lots of conflicts. I hope you guys can learn and cultivate a good habit of using git, I got some traumatic experiences before I truly understood how to use git co-working with a team, hahaha.

Remember to create an issue for this week's assignments and attach the PR link. Let me know if you bumped into any problems. Have a great weekend and good luck.
@emily1129 @river1440-ce @GSLiTW

**Comment by river1440-ce** [comment]
@tienyulin Really thanks for the kind and detailed explanation you made above to guide us how to use git properly. I will try to follow the pattern you mention (like create child branch more often, or never touch the branch which didn't belong to myself) 

As you state, it always make me nervous to solve any conflict, which then make me prefer working on the same branch for a long time (just want to avoid merging and the potential conflict) But I will keep trying to develop a good habit for creating more child branches and PRs.

Thanks again for your advice, it is really useful!
